name: Build and Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json     

      - name: Install dependencies        
        run: |
          pwd
          ls -la
          cd frontend
          ls -la
          npm ci

      - name: Build with Next.js
        run: |
          cd frontend
          npm run build

      - name: List output files
        run: |
          cd frontend
          ls -la
          echo "Listing the content of the out directory"
          ls -la out

      - name: Upload artifact for deployment
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./frontend/out

  deploy:
    if: github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
